### PR TITLE
Add a tool to get download stats

### PR DESCRIPTION
**Pull request by aiuto**
It is a separate program for now, since I think I want to run it off of a different set of repositories.

Right now I just want to get the stats and see what they look like. I think they are quite noisy.
If I can make sense of them, I will start storing them in cloud sql and we can turn them in to trend plots.

### CODE REVIEW

**Review by dslomov — APPROVED** [review]
\o/ awesome!

**Comment by jin** [comment]
I think this broke issue-stats.py update, both for --full and incremental

**Comment by aiuto** [comment]
I will look again right now. I tested update right before sending the PR.
Perhaps not --full.

**Comment by aiuto** [comment]
Weird. Update works, but then flakes out on some of the repos.  With a 502.
What were you seeing?

updating https://api.github.com/repos/bazelbuild/bazel-toolchains/issues/474
updating https://api.github.com/repos/bazelbuild/bazel-toolchains/issues/470
Fetching issues changed since: 2019-05-01T23:12:34Z
0
Fetching issues changed since: 2019-05-01T23:12:34Z
6
new issue https://api.github.com/repos/bazelbuild/buildtools/issues/626
new issue https://api.github.com/repos/bazelbuild/buildtools/issues/625
updating https://api.github.com/repos/bazelbuild/buildtools/issues/614
updating https://api.github.com/repos/bazelbuild/buildtools/issues/612
updating https://api.github.com/repos/bazelbuild/buildtools/issues/611
new issue https://api.github.com/repos/bazelbuild/buildtools/issues/477
Fetching issues changed since: 2019-05-01T23:12:34Z
Traceback (most recent call last):
  File "./issue-stats.py", line 139, in <module>
    main()
  File "./issue-stats.py", line 128, in main
    update(args.full)
  File "./issue-stats.py", line 57, in update
    new_issues = github.fetch_issues(repo, "", modified_after=db_time)
  File "/usr/local/google/home/aiuto/ws/bazel-gardening-tools/github.py",
line 67, in fetch_issues
    response = urllib.request.urlopen(add_client_secret(url))
  File "/usr/lib/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.6/urllib/request.py", line 532, in open
    response = meth(req, response)
  File "/usr/lib/python3.6/urllib/request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.6/urllib/request.py", line 570, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 650, in
http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 502: Bad Gateway
Makefile:13: recipe for target 'update' failed

**Comment by jin** [comment]
My bad, I didn't realize the print logging was removed for --full with _DEBUG. 

All is good!

**Pull request merged**
